[package]
edition = "2021"
license = "MIT or Apache-2.0"
name    = "nomos_risc0_proofs"
version = "0.1.0"

[build-dependencies]
risc0-build = "1.2.0"

[package.metadata.risc0]
methods = ["bundle_balance", "covenant_nop", "proof_of_leadership", "ptx"]

[package.metadata.cargo-machete]
# cargo-machete does not yet handle build-time dependencies -> https://github.com/bnjbvr/cargo-machete/issues/100
ignored = ["risc0-build"]
