[package]
name = "nomos_cl_risc0_proofs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0" }

[package.metadata.risc0]
methods = ["bundle", "covenant_nop", "ptx"]

