[package]
name = "nomos-core"
version = "0.1.0"
edition = "2021"
authors = [
    "Daniel Sanchez Quiros <danielsq@status.im>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1" }
bytes = "1.3"
futures = "0.3"
nomos-network = { path = "../nomos-services/network", optional = true }
raptorq = { version = "1.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
bincode = "1.3"
once_cell = "1.0"

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.23", features = ["macros", "rt"] }


[features]
default = []
raptor = ["raptorq"]
mock = ["nomos-network/mock"]
