[package]
name = "covenant_nop"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0", default-features = false, features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
cl = { path = "../../cl" }
nomos_proof_statements = { path = "../../proof_statements" }
