[package]
name = "nomos-http"
version = "0.1.0"
edition = "2021"

[[example]]
name = "axum"
path = "examples/axum.rs"
required-features = ["http"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", optional = true }
async-trait = "0.1"
bytes = "1.3"
clap = { version = "4", features = ["derive", "env"], optional = true }
futures = "0.3"
hyper = { version = "0.14", optional = true }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", branch = "main" }
overwatch-derive = { git = "https://github.com/logos-co/Overwatch", branch = "main" }
parking_lot = { version = "0.12", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
thiserror = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber =  { version = "0.3", features = ["json"] }
tracing-gelf = "0.7"
tower = { version = "0.4", optional = true }
tower-http = { version = "0.3", features = ["cors", "trace"] }
tokio = { version = "1", features = ["sync", "macros"] }

[features]
default = []
http = ["clap", "axum", "serde_json", "parking_lot", "hyper"]
