repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        entry: cargo +nightly-2025-01-03 fmt
      - id: clippy
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.18.0
    hooks:
      - id: cargo-deny
        args:
          - check
          - --hide-inclusion-graph
          - -c
          - .cargo-deny.toml
          - --show-stats
          - -D
          - warnings
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
