[package]
edition = "2021"
license = { workspace = true }
name    = "executor-http-client"
version = "0.1.0"

[dependencies]
nomos-core     = { workspace = true }
nomos-executor = { workspace = true }
reqwest        = "0.12"
serde          = "1.0"
thiserror      = "1.0"
