[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-blend-network"
version = "0.1.0"

[dependencies]
cached              = "0.53.1"
futures             = "0.3.30"
libp2p              = { workspace = true }
nomos-blend         = { workspace = true }
nomos-blend-message = { workspace = true }
sha2                = "0.10"
tokio               = { version = "1", features = ["time"], optional = true }
tokio-stream        = { version = "0.1", optional = true }
tracing             = "0.1"

[dev-dependencies]
fixed        = "1"
libp2p       = { workspace = true, features = ["ed25519", "quic", "tokio"] }
tokio        = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"

[features]
default = ["tokio"]
tokio   = ["dep:tokio", "dep:tokio-stream"]
