[package]
edition = "2021"
license = { workspace = true }
name    = "full-replication"
version = "0.1.0"

[features]
default = []
openapi = ["dep:utoipa", "serde_json"]

[dependencies]
blake2     = { version = "0.10" }
bytes      = { version = "1.3", features = ["serde"] }
nomos-core = { workspace = true }
serde      = { version = "1.0", features = ["derive"] }

serde_json = { version = "1.0", optional = true }
utoipa     = { version = "4.0", optional = true }
