[package]
name = "full-replication"
version = "0.1.0"
edition = "2021"

[features]
openapi = ["dep:utoipa", "serde_json"]

[dependencies]
blake2 = { version = "0.10" }
bytes = { version = "1.3", features = ["serde"] }
nomos-core = { path = "../../nomos-core" }
serde = { version = "1.0", features = ["derive"] }

utoipa = { version = "4.0", optional = true }
serde_json = { version = "1.0", optional = true }
