mixnode:
  # A listen address for other mixnodes in the mixnet and mixclients who want to send packets.
  listen_address: 0.0.0.0:7777
  # A (internal) listen address only for a "single" mixclient who wants to receive packets
  # from the last mixnet layer.
  # For more details, see the documentation in the "mixnet" crate.
  client_listen_address: 0.0.0.0:7778
  # A ed25519 private key for decrypting inbound Sphinx packets
  # received from mixclients or mixnodes in the previous mixnet layer.
  private_key: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  # A max number of connections that will stay connected to mixnodes in the next layer.
  connection_pool_size: 255
log:
  backend: "Stdout"
  format: "Json"
  level: "debug"
