[package]
name = "nomos-mix"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.53"
tokio = { version = "1.39" }
tracing = "0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
nomos-mix-message = { path = "../message" }
futures = "0.3"
