[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-blend-message"
version = "0.1.0"

[dependencies]
itertools     = "0.13"
rand_chacha   = "0.3"
sha2          = "0.10"
sphinx-packet = "0.2"
thiserror     = "1.0.65"
x25519-dalek  = { version = "2.0.1", features = ["getrandom", "serde", "static_secrets"] }

[dev-dependencies]
nomos-core = { workspace = true }
