[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-messages"
version = "0.1.0"

[dependencies]
futures       = "0.3.31"
kzgrs-backend = { workspace = true }
nomos-core    = { workspace = true }
serde         = { version = "1.0.215", features = ["derive"] }
tokio         = "1"

[dev-dependencies]
kzgrs-backend = { workspace = true, features = ["testutils"] }
tokio         = { version = "1", features = ["macros"] }
