[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-network-service"
version = "0.1.0"

[dependencies]
async-trait              = "0.1"
futures                  = "0.3"
kzgrs-backend            = { workspace = true }
libp2p                   = { version = "0.55", features = ["ed25519"] }
log                      = "0.4.22"
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-tracing            = { workspace = true }
overwatch-rs             = { workspace = true }
serde                    = { version = "1.0", features = ["derive"] }
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
tokio                    = { version = "1", features = ["macros", "sync"] }
tokio-stream             = "0.1"
tracing                  = "0.1"
