[package]
name = "nomos-utils"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
const-hex = "1"
serde = { version = "1.0", optional = true }
rand = "0.8"
rand_chacha = "0.3"
