on:
  push:
    branches:
      - my-codecov
      - master
  workflow_dispatch:

name: My Codecov 3

jobs:
  test:
    name: Test
    env:
      RUSTFLAGS: -C instrument-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout submodules
        run: git submodule update --init --recursive 
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install risc0
        run: cargo binstall -y cargo-risczero && cargo risczero install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --no-default-features --features libp2p
      - uses: actions-rs/cargo@v1
      - run: |
          mkdir bcp
          cp ./target/debug/{nomos-cli, nomos-node, rocks} bcp/
          cargo clean
          mkdir -p target/debug
          cp bcp/* ./target/debug/
      - uses: actions-rs/cargo@v1
        continue-on-error: true
      - run: |
          cargo binstall -y grcov;
          cargo test --no-default-features --features libp2p
          mkdir /tmp/cov;
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o /tmp/cov/tests.lcov;
        env:
          SLOW_TEST_ENV: true
          RISC0_DEV_MODE: true
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: integration-test-artifacts
          path: tests/.tmp*
      - uses: codecov/codecov-action@v4.0.1
        with:
          directory: /tmp/cov/
          name: nomos-node-codecov
          token: ${{ secrets.CODECOV_TOKEN }}

