on:
  schedule:
    - cron: '0 0 * * *'
  

name: Nightly consensus tests

jobs:
  test:
    name: Test Suite
    strategy:
      fail-fast: false # all OSes should be tested even if one fails (default: true)
      matrix:
        feature: [ libp2p, "libp2p,mixnet" ]
        os: [ ubuntu-latest, macos-latest-xlarge ] # drop windows for now as risc0 does not support it
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --no-default-features --features ${{ matrix.feature }}
      - name: Integration tests
        uses: actions-rs/cargo@v1
        env:
          CONSENSUS_SLOT_TIME: 260 # cpu only proving on ci machines is quite slow
        with:
          command: test
          args: --manifest-path tests/Cargo.toml --no-default-features --features ${{ matrix.feature }},prove
      - name: Ignored tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --ignored
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: integration-test-artifacts
          path: tests/.tmp*
    
  risc0:
    name: Risc0 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install risc0
        run: cargo install cargo-risczero && cargo risczero install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path proof_of_leadership/risc0/prover/Cargo.toml
      
